ln -s ../../CharTouch/web/back_icon.png
ln -s ../../CharTouch/web/data1m.js
ln -s ../../CharTouch/web/galaxy.png
ln -s ../../CharTouch/web/game.js
ln -s ../../CharTouch/web/index.html
ln -s ../../CharTouch/web/index_j.html
ln -s ../../CharTouch/web/ipad.css
ln -s ../../CharTouch/web/ipad_setting.css
ln -s ../../CharTouch/web/iphone4.css
ln -s ../../CharTouch/web/iphone4_setting.css
ln -s ../../CharTouch/web/main.css
ln -s ../../CharTouch/web/redo_icon.png
ln -s ../../CharTouch/web/setting.html
ln -s ../../CharTouch/web/setting.js
ln -s ../../CharTouch/web/setting_icon.png
ln -s ../../CharTouch/web/setting_j.html
ln -s ../../CharTouch/web/ship_plate.png
ln -s ../../CharTouch/web/silver_plate.png
ln -s ../../CharTouch/web/space_kana.png
ln -s ../../CharTouch/web/space_kana_icon.png
ln -s ../../CharTouch/web/space_math.png
ln -s ../../CharTouch/web/space_math_bk.png
ln -s ../../CharTouch/web/spaceback.png
ln -s ../../CharTouch/web/spaceship.png
ln -s ../../CharTouch/web/ufo.png
